### ISSUE TITLE
aws_resource_missing_tags errors when tags are provided via default_tags mechanism

### ISSUE THREAD

**Issue by mbazalik** [terraform-linters/tflint-ruleset-aws#117]
Aws have provided a new way of providing default tags through aws provider.

Right now those are ignored by `aws_resource_missing_tags` rule.

Would it be for the rule not to error if the tags are present in the provider?

Thank you

**Comment by wata727** [comment]
Yes, this rule doesn't currently support the default tags.
https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

On the other hand, this rule is just for manually solving the problem that should be realized with the default tags, and I think that this rule is no longer necessary. What do you think?

**Comment by idNoRD** [comment]
This rule is still necessary for these use cases:

1) When you have many providers with default_tags but one of them missing default_tags.
2) Make sure that all default_tags in all providers contain a required Tag.

The rule should error if the tags are not present in a resource and are not present in the corresponding provider.
