### ISSUE TITLE
`aws_iam_policy_sid_invalid_characters` fails when policy isn't evaluable.

### ISSUE THREAD

**Issue by MrJoy** [terraform-linters/tflint-ruleset-aws#177]
I have Terraform code of this form:

```terraform
data "aws_iam_policy_document" "ecr_readonly" {
  statement {
    sid       = "authorization"
    actions   = ["ecr:GetAuthorizationToken"]
    resources = ["*"]
  }

  statement {
    sid = "pullimages"

    actions = [
      "ecr:ListImages",
      "ecr:GetDownloadUrlForLayer",
      "ecr:DescribeRepositories",
      "ecr:DescribeImages",
      "ecr:BatchGetImage",
      "ecr:BatchCheckLayerAvailability"
    ]

    resources = [
      aws_ecr_repository.repo1.arn,
      aws_ecr_repository.repo2.arn
    ]
  }
}

resource "aws_iam_policy" "ecr_readonly" {
  name = join("-", [local.env, "ecr", "readonly"])
  path = join("/", ["", local.env, ""])

  policy = data.aws_iam_policy_document.ecr_readonly.json
}
```

When I run tflint 0.31.0 using tflint-ruleset-aws 0.7.0, it fails with this error:

```
Error: Failed to check `aws_iam_policy_sid_invalid_characters` rule: unexpected end of JSON input
```

Running with debug info, I see this:

```
...
2021-09-01T18:04:00.230-0700 [DEBUG] plugin.tflint-ruleset-aws: 2021/09/01 18:04:00 [DEBUG] Walk `aws_iam_policy.*.policy` attribute
18:04:00 runner_walk.go:36: [DEBUG] Walk `aws_iam_policy.repo2.policy` attribute
18:04:00 runner_walk.go:36: [DEBUG] Walk `aws_iam_policy.repo1.policy` attribute
18:04:00 runner_eval.go:73: [INFO] Unevaluable expression found in logging.tf:49. TFLint ignores unevaluable expressions.
Failed to check ruleset. An error occurred:

Error: Failed to check `aws_iam_policy_sid_invalid_characters` rule: unexpected end of JSON input
```

It seems like this rule isn't prepared for condition where it doesn't have actual access to the policy document, perhaps?

**Comment by MrJoy** [comment]
Also: `# tflint-ignore: aws_iam_policy_sid_invalid_characters` doesn't seem to be helping to disable this check.  Not entirely sure how to proceed other than downgrading the ruleset. :-/

**Comment by wata727** [comment]
Thank you for reporting this. Yes, this is a bug.
I'm planning to release v0.7.1. Please try it again.

> Also: # tflint-ignore: aws_iam_policy_sid_invalid_characters doesn't seem to be helping to disable this check.

This is the intended behavior, as the `tflint-ignore` annotation is a way to control warnings, not internal errors. Such errors are usually fixed quickly, so it's a good idea to downgrade temporarily and wait for the new patch release.

**Comment by MrJoy** [comment]
Thank you so much for the prompt response, the guidance, and the fix!
