### ISSUE TITLE
Check that subnet CIDR are within VPC CIDR range(s)

### ISSUE THREAD

**Issue by lordz-md** [terraform-linters/tflint-ruleset-aws#184]
I was testing tflint with some code the other days and while it catches a lot of things one thing that caught my attention is that I use VPC CIDR 10.30.0.0/16, but one of the subnet CIDR's is 10.35.5.0/24, and I am not getting any error about that. Can we somehow know if one of our subnets is mismatching the VPC CIDR.

**Comment by bendrucker** [comment]
Please do submit a PR if you're interested in this as we don't generally work on rule requests outside of core Terraform rules
