### ISSUE TITLE
aws_resource_missing_tags doesn't read `tags_all`

### ISSUE THREAD

**Issue by lays147** [terraform-linters/tflint-ruleset-aws#303]
Hi, 
In our company we are using TFLint with a set of rules. One of them is to check the tags in the terraform code. However, I've noticed that the `default_tags` -> `tags_all` used in the aws provider are not considered when evaluating the rule. 

What would be the way to fix it? I may push a PR if you point me out. 

I was able to find that the name of the variable is defined [here](https://github.com/terraform-linters/tflint-ruleset-aws/blob/master/rules/aws_resource_missing_tags.go#L28), but my Golang knowledge is short to understand all the logic defined there.

Cheers,

**Comment by wata727** [comment]
Duplicate of https://github.com/terraform-linters/tflint-ruleset-aws/issues/192

The logic for getting the `default_tags` is a bit complicated and probably not an easy fix. The SDK's documentation may be helpful.
https://pkg.go.dev/github.com/terraform-linters/tflint-plugin-sdk

However, I'm currently planning a major update to the plugin API, which may be better after it is complete.

**Comment by PatMyron** [comment]
pinned #117 for visibility
