### ISSUE TITLE
Failed to check ruleset; unevaluable expression found

### ISSUE THREAD

**Issue by suzuki-shunsuke** [terraform-linters/tflint-ruleset-aws#326]
## Overview

tflint failed due to the error `Failed to check ruleset; unevaluable expression found`.

```console
Failed to check ruleset; unevaluable expression found in terraform.tf:12
```

## How to reproduce

terraform.tf

```tf
terraform {
  required_version = ">= 0.15"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.1.0"
    }
  }
}

provider "aws" {
  region      = local.region # Use local value
  max_retries = 3
}

locals {
  region = "ap-northeast-1"
}
```

.tflint.hcl

```hcl
plugin "aws" {
  enabled = true
  version = "0.13.1"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"

  deep_check = true # When deep_check is false, this issue can't be reproduced
}
```

It fails to run `tflint` as the following.

```console
$ tflint
Failed to check ruleset; unevaluable expression found in terraform.tf:12
```

If `deep_check` is false, the error doesn't occur.

And when tflint and aws plugin are downgraded, the error doesn't occur too.

```console
$ tflint -v
TFLint version 0.34.1
+ ruleset.aws (0.12.0)
```

```console
$ tflint # the error doesn't occur
```

## Version

```console
$ terraform version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
```

```console
$ tflint -v
TFLint version 0.35.0
+ ruleset.aws (0.13.1)
```

## Reference

* https://github.com/terraform-linters/tflint/issues/571#issuecomment-570786108
  * > Yes. TFLint skips inspection for expression containing local values because the expression may contain unknown values like the following:

**Comment by wata727** [comment]
Fixed in https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.13.2

**Comment by wata727** [comment]
> Parsing means correctly interpreting the declaration, not just not erroring. The configuration remains unparseable, the error is just suppressed. For most users, that represents a silent failure.

Makes sense. There may be room for improvement if the precondition fails.

Originally, the reason for referring to the attributes of the provider block is that I thought that the credentials used by deep checking should be the same as the credentials at running `terraform apply`.

I'm not sure if it's better to add a config like `use_provider_block` or just make an error. Perhaps it might be a good idea to simply not refer to the provider block.

**Comment by bendrucker** [comment]
> Originally, the reason for referring to the attributes of the provider block is that I thought that the credentials used by deep checking should be the same as the credentials at running terraform apply.

Yes, I agree with this. For most users this is the most straightforward. 

Some users could be referencing provider config that is only available at plan time, e.g. a role ARN from remote state. In those cases, I think it makes the most sense to refuse to parse the provider block entirely and require the user to pass credentials/config. What seems off to me is the idea that some attributes would be parsed but others would be ignored.
