### ISSUE TITLE
Does not work with child modules and variables

### ISSUE THREAD

**Issue by pragya-nayak** [terraform-linters/tflint-ruleset-aws#370]
tflint is working only on resource and not on child modules and when tfvars are used. It does not give any output in this case.

**Comment by wata727** [comment]
You can use the module inspection and the `--var-file` option.
https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/user-guide/module-inspection.md
https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/user-guide/config.md#varfile

**Comment by RichardBradley** [comment]
Shouldn't this be on by default?

Presumably most or all people who want linting will want their invoked modules linted too? This took me 10 mins to find and isn't hinted at in the main README
