### ISSUE TITLE
Add Node 18 Support

### ISSUE THREAD

**Issue by BjoernSaja** [terraform-linters/tflint-ruleset-aws#402]
## Description

AWS announced NodeJS v18 runtime support. Could you please add `nodejs18.x` to the list of valid runtime values.

## References

 - https://aws.amazon.com/de/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
 - https://github.com/terraform-linters/tflint-ruleset-aws/blob/master/rules/models/aws_lambda_function_invalid_runtime.go#L35

**Comment by wata727** [comment]
Fixed in v0.20.0
https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.20.0
