### ISSUE TITLE
Provide java17 as AWS Lambda Runtime

### ISSUE THREAD

**Issue by timomeinen** [terraform-linters/tflint-ruleset-aws#486]
AWS Lambda runtime `java17` is available now:

https://aws.amazon.com/de/about-aws/whats-new/2023/04/aws-lambda-java-17/

But tflint gives the following error:

    Error: "java17" is an invalid value as runtime (aws_lambda_function_invalid_runtime)
      on lambda.tf line 8:
      8:   runtime          = "java17"

**Comment by timomeinen** [comment]
@bendrucker When will you release a new version of the changes in #485? We would love to switch to "java17" with the lambdas.

**Comment by wata727** [comment]
I was planning to release v0.23.1, but it has been put on hold for other reasons. Please follow https://github.com/terraform-linters/tflint-ruleset-aws/issues/496.
