### ISSUE TITLE
aws_iam_role_invalid_path should allow empty string

### ISSUE THREAD

**Issue by unacceptable** [terraform-linters/tflint-ruleset-aws#50]
## Problem statement
When writing a terraform module with a `var.path` as the IAM Role path the following error is thrown:

```console
2 issue(s) found:

Error: path must be 1 characters or higher (aws_iam_role_invalid_path)

  on iam.tf line 38:
  38:   path               = var.path

Error: "" does not match valid pattern ^(\x{002F})|(\x{002F}[\x{0021}-\x{007F}]+\x{002F})$ (aws_iam_role_invalid_path)

  on iam.tf line 38:
  38:   path               = var.path
```

I believe that the regex pattern should be something like: `(^(\x{002F})|(\x{002F}[\x{0021}-\x{007F}]+\x{002F})$|^$)` to account for modules with variables that default to empty strings (which the provider will really default to `/`).

## Version

```console
TFLint version 0.23.1
+ ruleset.aws (0.1.2-bundled)
```

**Comment by bendrucker** [comment]
If you intend for the value to be unset and for a provider or upstream default to be used, it's better to use `null`. You can have a look at how the roles in this repo are generated. A change would have broader implications and wouldn't just apply to this one rule.

**Comment by unacceptable** [comment]
@bendrucker,

I didn't know that was a thing.  I will have to give that a try.  Thanks for the information.

Respectfully,
Robert J.
