### ISSUE TITLE
Recursive module linting fails with `module is not found`

### ISSUE THREAD

**Issue by kayman-mk** [terraform-linters/tflint-ruleset-aws#521]
Hi,

using #518 as base but adding a module m to `m/main.tf`. `terraform apply` works fine and applies all changes, but `tflint --recursive --module` fails with

```
tflint --module --recursive
Failed to load configurations; m\main.tf:40,1-11: `m` module is not found. Did you run `terraform init`?; :

Error: `m` module is not found. Did you run `terraform init`?

  on m\main.tf line 40, in module "m":
  40: module "m" {
```

Layout on filesystem is
```
main.tf
  m/main.tf
    m/main.tf
```

It seems that everything is fine if I rename the second submodule to something different than `m`..

Ruleset version is 0.24.3

**Comment by wata727** [comment]
This is the intended behavior. The `--recursive` runs `tflint --module` on every module, so you need to run `terraform init` on every module (`./`, `./m`, and `./m/m`).
