### ISSUE TITLE
db.m6idn instance type is reported as invalid

### ISSUE THREAD

**Issue by GeorgeSimpsonAtFanatics** [terraform-linters/tflint-ruleset-aws#590]
TF Lint errors with the message:
 `Error - "db.m6idn.32xlarge" is invalid instance type. (aws_db_instance_invalid_type)`

AWS documentation include valid instnace types for the `db.m6idn` family:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html

**Comment by wata727** [comment]
@GeorgeSimpsonAtFanatics Thank you for reporting this.
https://github.com/GeorgeSimpsonAtFanatics/tflint-ruleset-aws/pull/1 seems reasonable. Can you submit a pull request to this repository?

**Comment by GeorgeSimpsonAtFanatics** [comment]
> Can you submit a pull request to this repository?

Submitted [PR #591](https://github.com/terraform-linters/tflint-ruleset-aws/pull/591)
