### ISSUE TITLE
List of taggable resources missing MSK Connect resources

### ISSUE THREAD

**Issue by barnharts4** [terraform-linters/tflint-ruleset-aws#669]
The list of taggable AWS resources in `rules/tags/resources.go` does not contain any of the taggable resources for AWS MSK Connect.  These resources are:
* [aws_mskconnect_connector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mskconnect_connector)
* [aws_mskconnect_custom_plugin](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mskconnect_custom_plugin)
* [aws_mskconnect_worker_configuration](aws_mskconnect_worker_configuration)

I would be happy to submit a PR, but I am unclear as to how AWS resource names are added to `resources.go`.  All the PRs that update that file seem to be in PRs called `Update AWS provider/module and generated content`, like [this one](https://github.com/terraform-linters/tflint-ruleset-aws/pull/656).

Does updating the version of `github.com/aws/aws-sdk-go` cause a build process to automatically update the list of taggable resources, or is this file updated manually?

Also, these three resources have existed for quite a while, so even if it is automatic, upgrading the SDK may still not add them.

**Comment by wata727** [comment]
Thank you for your contribution.

The `resources.go` is automatically generated from the Terraform schema, so there is no need to update it manually. AWS MSK Connect resources will be added in https://github.com/terraform-linters/tflint-ruleset-aws/pull/660.
We will publish the next version soon, so please wait until then.

**Comment by barnharts4** [comment]
Thank you for the followup.  Do you have a rough estimate on what "soon" is?  I see #660 has been open for two months.

**Comment by wata727** [comment]
It's about a few days.
v0.33.0 has been released.
https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.33.0

**Comment by barnharts4** [comment]
Excellent, thank you!
