### ISSUE TITLE
nodejs14.x runtime support 

### ISSUE THREAD

**Issue by vinothvk** [terraform-linters/tflint-ruleset-aws#72]
Hello team

May i know when the below nodejs14.x support will be available in tflint ?
currently i am getting aws_lambda_function_invalid_runtime error while using nodejs14.x with tflint 0.24.1
Thanks

https://github.com/terraform-linters/tflint-ruleset-aws/blob/master/rules/models/aws_lambda_function_invalid_runtime.go#L32

**Comment by circa10a** [comment]
I believe @wata727 said releases will be once a month. So should be available in a week if we're sticking to the schedule

**Comment by wata727** [comment]
Yeah, we release new features once a month, but this is not the case if you are faced with such false positives.

However, the main way to use the plugin is the bundled plugin, which will be released once a month, and I'm planning to update the API definitions at that timing considering that the next release is near.

**Comment by wata727** [comment]
AWS ruleset v0.3.0 and TFLint v0.25.0 (includes AWS ruleset v0.3.0) are released.
