### ISSUE TITLE
Documentation for new `gov_friendly_arns` rules is misnamed

### ISSUE THREAD

**Issue by gdavison** [terraform-linters/tflint-ruleset-aws#97]
v.0.3.0 introduces three new GovCloud-friendly ARN rules, from PR #55,

* `aws_iam_policy_document_gov_friendly_arns`
* `aws_iam_policy_gov_friendly_arns`
* `aws_iam_role_policy_gov_friendly_arns`

The documentation for these rules drops the `_arns` from the end.

**Comment by wata727** [comment]
Thanks. Fixed in https://github.com/terraform-linters/tflint-ruleset-aws/pull/100
